In [51]:
d = {1:'a', 2:'b',3: 'c'}

In [52]:
s = list(d.keys())
s

[1, 2, 3]

In [3]:
import numpy as np
from numpy.random import choice

In [54]:
probs = [0.6, 0.2, 0.2]
draw = choice(s, 1, p=probs)
draw

array([2])

In [55]:
rm_idx = s.index(draw)
s.pop(rm_idx)
probs.pop(rm_idx)

0.2

In [56]:
s

[1, 3]

In [57]:
probs

[0.6, 0.2]

In [58]:
np.array(probs) / np.sum(probs)

array([0.75, 0.25])

In [61]:
np.sum(list(d.keys()))

6

In [6]:

n = np.array([1] * 10) / 10
n.tolist()

[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

In [70]:
p = np.array([1,2,3,5])
p = p / 5
p

array([0.2, 0.4, 0.6, 1. ])

In [78]:
n = np.array(list(d.values()))
n

array(['a', 'b', 'c'], dtype='<U1')

In [86]:
np.array(list(d.keys())) / np.sum(list(d.keys()))

array([0.16666667, 0.33333333, 0.5       ])

In [76]:
list(d.keys())

[1, 2, 3]

In [88]:
d = {1:2.5,2:3.6,3:4.7}
np.array(list(d.values())) / np.sum(list(d.values()))

array([0.23148148, 0.33333333, 0.43518519])

In [97]:
import random
import math
def probabilistic_round(value):
    integer_part = math.floor(value)
    fractional_part = value - integer_part
    return integer_part + 1.0 if random.random() < fractional_part else integer_part + 0.0

In [4]:
from itertools import count

In [9]:
cntr = count(0)

In [10]:
for _ in range(5):
    print(next(cntr))

0
1
2
3
4


In [16]:
def roll_over_d(d):
    for x, y in d.items():
        print(x, y)
        
d = {1:'a', 2:'b', 3:'c', 4:'d'}
for i, (x, y) in enumerate(d.items()):
    print(i, x, y)

0 1 a
1 2 b
2 3 c
3 4 d


In [1]:
import random
import numpy as np

In [70]:
c1_set, c2_set = {1: 'a', 2: 'b', 3: 'c'}, {1: 'd', 6: 'e', 2: 'f', 7: 'g'}

In [57]:
l1 = [1,2,4,5,6,8,10,11,13,14]

In [64]:
l2 = [1,3,4,5,7,9,10,12,15,16]

In [65]:
if len(l1) < len(l2):
    l1.extend([-1] * (max(len(l1), len(l2)) - min(len(l1), len(l2))))
else:
    l2.extend([-1] * (max(len(l1), len(l2)) - min(len(l1), len(l2))))

In [66]:
l1

[1, 2, 4, 5, 6, 8, 10, 11, 13, 14]

In [67]:
l2

[1, 3, 4, 5, 7, 9, 10, 12, 15, 16]

In [68]:
pairs = []
for x, y in zip(l1, l2):
    if x == -1 or y == -1:
        pairs.append((x, y))
        continue
        
    if x == y:
        pairs.append((x, y))
    else:
        pairs.append((x, -1))
        pairs.append((-1, y))

In [69]:
pairs

[(1, 1),
 (2, -1),
 (-1, 3),
 (4, 4),
 (5, 5),
 (6, -1),
 (-1, 7),
 (8, -1),
 (-1, 9),
 (10, 10),
 (11, -1),
 (-1, 12),
 (13, -1),
 (-1, 15),
 (14, -1),
 (-1, 16)]

In [72]:
'a' in c1_set

False

In [75]:
def creates_cycle(connections, test):
    i, o = test
    if i == o:
        return True

    visited = {o}
    while True:
        num_added = 0
        for a, b in connections:
            if a in visited and b not in visited:
                print(visited)
                if b == i:
                    return True

                visited.add(b)
                num_added += 1

        if num_added == 0:
            return False

In [81]:
creates_cycle([(1,2), (2,3), (3,4), (3,5), (5,6), (6,7)], (7,2))

{2}
{2, 3}
{2, 3, 4}
{2, 3, 4, 5}
{2, 3, 4, 5, 6}


True