In [51]:
d = {1:'a', 2:'b',3: 'c'}

In [52]:
s = list(d.keys())
s

[1, 2, 3]

In [3]:
import numpy as np
from numpy.random import choice

In [54]:
probs = [0.6, 0.2, 0.2]
draw = choice(s, 1, p=probs)
draw

array([2])

In [55]:
rm_idx = s.index(draw)
s.pop(rm_idx)
probs.pop(rm_idx)

0.2

In [56]:
s

[1, 3]

In [57]:
probs

[0.6, 0.2]

In [58]:
np.array(probs) / np.sum(probs)

array([0.75, 0.25])

In [61]:
np.sum(list(d.keys()))

6

In [6]:

n = np.array([1] * 10) / 10
n.tolist()

[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

In [70]:
p = np.array([1,2,3,5])
p = p / 5
p

array([0.2, 0.4, 0.6, 1. ])

In [78]:
n = np.array(list(d.values()))
n

array(['a', 'b', 'c'], dtype='<U1')

In [86]:
np.array(list(d.keys())) / np.sum(list(d.keys()))

array([0.16666667, 0.33333333, 0.5       ])

In [76]:
list(d.keys())

[1, 2, 3]

In [88]:
d = {1:2.5,2:3.6,3:4.7}
np.array(list(d.values())) / np.sum(list(d.values()))

array([0.23148148, 0.33333333, 0.43518519])

In [97]:
import random
import math
def probabilistic_round(value):
    integer_part = math.floor(value)
    fractional_part = value - integer_part
    return integer_part + 1.0 if random.random() < fractional_part else integer_part + 0.0

In [4]:
from itertools import count

In [9]:
cntr = count(0)

In [10]:
for _ in range(5):
    print(next(cntr))

0
1
2
3
4


In [16]:
def roll_over_d(d):
    for x, y in d.items():
        print(x, y)
        
d = {1:'a', 2:'b', 3:'c', 4:'d'}
for i, (x, y) in enumerate(d.items()):
    print(i, x, y)

0 1 a
1 2 b
2 3 c
3 4 d


In [1]:
import random
import numpy as np

In [9]:
c1_set, c2_set = {1: 'a', 2: 'b', 3: 'c'}, {1: 'd', 6: 'e', 2: 'f', 7: 'g'}

In [57]:
l1 = [1,2,4,5,6,8,10,11,13,14]

In [64]:
l2 = [1,3,4,5,7,9,10,12,15,16]

In [65]:
if len(l1) < len(l2):
    l1.extend([-1] * (max(len(l1), len(l2)) - min(len(l1), len(l2))))
else:
    l2.extend([-1] * (max(len(l1), len(l2)) - min(len(l1), len(l2))))

In [66]:
l1

[1, 2, 4, 5, 6, 8, 10, 11, 13, 14]

In [67]:
l2

[1, 3, 4, 5, 7, 9, 10, 12, 15, 16]

In [68]:
pairs = []
for x, y in zip(l1, l2):
    if x == -1 or y == -1:
        pairs.append((x, y))
        continue
        
    if x == y:
        pairs.append((x, y))
    else:
        pairs.append((x, -1))
        pairs.append((-1, y))

In [69]:
pairs

[(1, 1),
 (2, -1),
 (-1, 3),
 (4, 4),
 (5, 5),
 (6, -1),
 (-1, 7),
 (8, -1),
 (-1, 9),
 (10, 10),
 (11, -1),
 (-1, 12),
 (13, -1),
 (-1, 15),
 (14, -1),
 (-1, 16)]

In [72]:
'a' in c1_set

False

In [75]:
def creates_cycle(connections, test):
    i, o = test
    if i == o:
        return True

    visited = {o}
    while True:
        num_added = 0
        for a, b in connections:
            if a in visited and b not in visited:
                print(visited)
                if b == i:
                    return True

                visited.add(b)
                num_added += 1

        if num_added == 0:
            return False

In [81]:
creates_cycle([(1,2), (2,3), (3,4), (3,5), (5,6), (6,7)], (7,2))

{2}
{2, 3}
{2, 3, 4}
{2, 3, 4, 5}
{2, 3, 4, 5, 6}


True

In [83]:
d = []
for i in range(10):
    d[i] = str(i)
d

{0: '0',
 1: '1',
 2: '2',
 3: '3',
 4: '4',
 5: '5',
 6: '6',
 7: '7',
 8: '8',
 9: '9'}

In [86]:
list(d.keys())[:5]

[0, 1, 2, 3, 4]

In [87]:
l = np.array([5,5,5,4])
l = l / np.sum(l)

In [88]:
l

array([0.26315789, 0.26315789, 0.26315789, 0.21052632])

In [89]:
l[0] = 0.0
l

array([0.        , 0.26315789, 0.26315789, 0.21052632])

In [90]:
l = l / np.sum(l)
l

array([0.        , 0.35714286, 0.35714286, 0.28571429])

In [40]:
import numpy as np
import random

In [41]:
l = [1,2,3,4,5]

In [53]:
for x in random.choices(l, k=3):
    print(x)

5
5
3


In [2]:
x = [1,2,3]
x[:0]

[]

In [3]:
sorted(x)

[1, 2, 3]

In [5]:
import random
import numpy as np

In [10]:
members = [1,2,3,4]
p = np.array([1,1,1]) / 3.0
member_parent_1 = np.random.choice(list(c1_set.keys()), 1, p=p)
member_parent_1

array([1])

In [1]:
import numpy as np
import timeit

x = range(1000)
# or 
#x = np.random.standard_normal(1000)

def pure_sum():
    return sum(x)

def numpy_sum():
    return np.sum(x)

n = 10000

t1 = timeit.timeit(pure_sum, number = n)
print('Pure Python Sum:', t1)
t2 = timeit.timeit(numpy_sum, number = n)
print('Numpy Sum:', t2)

Pure Python Sum: 0.1532475647415019
Numpy Sum: 1.1720797273597179


In [19]:
node_ids = {'all': set([1,2,3,4,5]), 'input': set([1,2]), 'hidden': set([3,4]), 'output': set([5])}
node_ids

{'all': {1, 2, 3, 4, 5}, 'hidden': {3, 4}, 'input': {1, 2}, 'output': {5}}

In [23]:
possible_connections = set()

In [33]:
for source_id in node_ids['input']:
    for target_id in node_ids['hidden']:
        possible_connections.add((source_id, target_id))
    for target_id in node_ids['output']:
        possible_connections.add((source_id, target_id))
        
for source_id in node_ids['hidden']:    
    for target_id in node_ids['hidden']:   
        possible_connections.add((source_id, target_id))
    for target_id in node_ids['output']:
        possible_connections.add((source_id, target_id))
          
possible_connections

{(1, 3),
 (1, 4),
 (1, 5),
 (2, 3),
 (2, 4),
 (2, 5),
 (3, 3),
 (3, 4),
 (3, 5),
 (4, 3),
 (4, 4),
 (4, 5)}

In [34]:
new_hidden_id = 6
node_ids['hidden'].add(6)
node_ids

{'all': {1, 2, 3, 4, 5}, 'hidden': {3, 4, 6}, 'input': {1, 2}, 'output': {5}}

In [37]:
for source_id in node_ids['input']:
    possible_connections.add((source_id, new_hidden_id))
for source_id in node_ids['hidden']:    
    for target_id in node_ids['hidden']:   
        possible_connections.add((source_id, target_id))
for target_id in node_ids['output']:
        possible_connections.add((new_hidden_id, target_id))
        
possible_connections

{(1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6)}

In [38]:
connections = set([(1,3),(1,4),(1,5),(1,6),(6,3),(6,4),(6,5),(6,6)])
connections

{(1, 3), (1, 4), (1, 5), (1, 6), (6, 3), (6, 4), (6, 5), (6, 6)}

In [39]:
possible_connections - connections

{(2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6)}

In [54]:
possible_connections

{(1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6)}

In [55]:
list(possible_connections)

[(6, 4),
 (1, 3),
 (2, 6),
 (3, 3),
 (4, 6),
 (6, 6),
 (4, 5),
 (4, 4),
 (1, 4),
 (6, 3),
 (1, 5),
 (2, 3),
 (1, 6),
 (4, 3),
 (3, 6),
 (2, 5),
 (3, 4),
 (2, 4),
 (6, 5),
 (3, 5)]

In [57]:
random.choice(list(possible_connections))

(6, 5)

In [5]:
n_list_1 = [0, 1, 2, 3]
n_list_2 = [0, 1, 3]

node_pairs = set()
for x in n_list_1:
    if x in n_list_2:
        node_pairs.add((x, x))
    else:
        node_pairs.add((x, -1))
        
for y in n_list_2:
    if y in n_list_1:
        node_pairs.add((y, y))
    else:
        node_pairs.add((-1, y))

In [6]:
node_pairs

{(0, 0), (1, 1), (2, -1), (3, 3)}

In [8]:
import numpy as np

In [10]:
np.random.choice([1,2,3], 6)

array([2, 2, 2, 2, 3, 2])