In [1]:
import pandas as pd
import numpy as np
import random
from sklearn.cluster import KMeans

In [2]:
distance = {k: random.random() for k in range(10)}

In [11]:
matrix = {k: [] for k in distance.keys()}
for k1, v1 in distance.items():
    for k2, v2 in distance.items():
        matrix[k2].append(v1-v2)

In [12]:
df = pd.DataFrame(matrix)
df.head(10)

0         1         2         3         4         5         6  \
0  0.000000 -0.162184 -0.068379 -0.603053 -0.432653 -0.721875  0.130584   
1  0.162184  0.000000  0.093805 -0.440869 -0.270469 -0.559691  0.292768   
2  0.068379 -0.093805  0.000000 -0.534674 -0.364274 -0.653496  0.198963   
3  0.603053  0.440869  0.534674  0.000000  0.170400 -0.118822  0.733637   
4  0.432653  0.270469  0.364274 -0.170400  0.000000 -0.289222  0.563237   
5  0.721875  0.559691  0.653496  0.118822  0.289222  0.000000  0.852459   
6 -0.130584 -0.292768 -0.198963 -0.733637 -0.563237 -0.852459  0.000000   
7  0.179671  0.017487  0.111292 -0.423382 -0.252982 -0.542204  0.310255   
8  0.205880  0.043696  0.137501 -0.397173 -0.226774 -0.515995  0.336464   
9 -0.026353 -0.188537 -0.094732 -0.629406 -0.459006 -0.748228  0.104231   

          7         8         9  
0 -0.179671 -0.205880  0.026353  
1 -0.017487 -0.043696  0.188537  
2 -0.111292 -0.137501  0.094732  
3  0.423382  0.397173  0.629406  
4  0.252982  0.226774  0.459006  
5  0.542204  0.515995  0.748228  
6 -0.310255 -0.336464 -0.104231  
7  0.000000 -0.026209  0.206024  
8  0.026209  0.000000  0.232233  
9 -0.206024 -0.232233  0.000000

In [17]:
x = [[0,0,0],[1,1,1],[2,2,2],[3,3,3],[4,4,4]]

In [18]:
clusters = KMeans(n_clusters=3, random_state=0).fit_predict(x)

In [21]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
df.values[0]

array([ 0.00000000e+00, -5.06606887e-02,  2.78685333e-01,  5.57824703e-01,
        4.01687064e-01,  3.90021916e-02,  2.84328316e-01, -1.72198261e-01,
        1.51204466e-01, -2.14898429e-01,  5.56682605e-02,  1.07457565e-01,
        5.35778589e-01,  1.62628198e-01,  3.23796736e-01, -1.43437776e-01,
       -1.10969525e-01,  3.64850592e-01,  7.42719930e-01,  3.69168288e-01,
        1.60461647e-01, -1.74712815e-03,  4.90042478e-01,  6.61221121e-01,
        8.07767094e-02, -1.67990845e-01,  4.15065521e-01, -8.85808532e-02,
        2.09284290e-01,  2.60497810e-01, -3.10987096e-02, -9.52294786e-02,
        1.48320887e-01,  2.15290322e-01, -1.29484037e-01, -1.98149704e-01,
        6.31523764e-01,  4.42261259e-01,  4.64052232e-01, -1.19402423e-01,
        6.52106261e-01, -1.10266332e-01,  4.77403394e-01, -1.49695584e-01,
       -1.45947179e-01,  1.80122745e-01,  2.46121890e-01,  2.31965890e-01,
        1.67923324e-01,  2.92365420e-01,  3.79242203e-01,  4.51122462e-03,
       -1.28534912e-01,  

In [1]:
import gym

In [15]:
env = gym.make('CartPole-v1')
for i_episode in range(20):
    observation = env.reset()
    fitness = []
    for t in range(100):
        # env.render()
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        fitness.append(reward)
        if done:
            print('reward {0}'.format(sum(fitness)))
            print("Episode finished after {} timesteps".format(t+1))
            break

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
reward 29.0
Episode finished after 29 timesteps
reward 18.0
Episode finished after 18 timesteps
reward 17.0
Episode finished after 17 timesteps
reward 18.0
Episode finished after 18 timesteps
reward 20.0
Episode finished after 20 timesteps
reward 14.0
Episode finished after 14 timesteps
reward 14.0
Episode finished after 14 timesteps
reward 11.0
Episode finished after 11 timesteps
reward 13.0
Episode finished after 13 timesteps
reward 24.0
Episode finished after 24 timesteps
reward 21.0
Episode finished after 21 timesteps
reward 12.0
Episode finished after 12 timesteps
reward 45.0
Episode finished after 45 timesteps
reward 22.0
Episode finished after 22 timesteps
reward 24.0
Episode finished after 24 timesteps
reward 18.0
Episode finished after 18 timesteps
reward 14.0
Episode finished after 14 timesteps
reward 15.0
Episode finished after 15 timesteps
reward 15.0
Episode finished after 15

In [8]:
env.action_space[0]

TypeError: 'Discrete' object does not support indexing

In [70]:
p = np.array([1,2,3,5])
p = p / 5
p

array([0.2, 0.4, 0.6, 1. ])

In [78]:
n = np.array(list(d.values()))
n

array(['a', 'b', 'c'], dtype='<U1')

In [86]:
np.array(list(d.keys())) / np.sum(list(d.keys()))

array([0.16666667, 0.33333333, 0.5       ])

In [76]:
list(d.keys())

[1, 2, 3]

In [88]:
d = {1:2.5,2:3.6,3:4.7}
np.array(list(d.values())) / np.sum(list(d.values()))

array([0.23148148, 0.33333333, 0.43518519])

In [97]:
import random
import math
def probabilistic_round(value):
    integer_part = math.floor(value)
    fractional_part = value - integer_part
    return integer_part + 1.0 if random.random() < fractional_part else integer_part + 0.0

In [4]:
from itertools import count

In [9]:
cntr = count(0)

In [10]:
for _ in range(5):
    print(next(cntr))

0
1
2
3
4


In [16]:
def roll_over_d(d):
    for x, y in d.items():
        print(x, y)
        
d = {1:'a', 2:'b', 3:'c', 4:'d'}
for i, (x, y) in enumerate(d.items()):
    print(i, x, y)

0 1 a
1 2 b
2 3 c
3 4 d


In [1]:
import random
import numpy as np

In [9]:
c1_set, c2_set = {1: 'a', 2: 'b', 3: 'c'}, {1: 'd', 6: 'e', 2: 'f', 7: 'g'}

In [57]:
l1 = [1,2,4,5,6,8,10,11,13,14]

In [64]:
l2 = [1,3,4,5,7,9,10,12,15,16]

In [65]:
if len(l1) < len(l2):
    l1.extend([-1] * (max(len(l1), len(l2)) - min(len(l1), len(l2))))
else:
    l2.extend([-1] * (max(len(l1), len(l2)) - min(len(l1), len(l2))))

In [66]:
l1

[1, 2, 4, 5, 6, 8, 10, 11, 13, 14]

In [67]:
l2

[1, 3, 4, 5, 7, 9, 10, 12, 15, 16]

In [68]:
pairs = []
for x, y in zip(l1, l2):
    if x == -1 or y == -1:
        pairs.append((x, y))
        continue
        
    if x == y:
        pairs.append((x, y))
    else:
        pairs.append((x, -1))
        pairs.append((-1, y))

In [69]:
pairs

[(1, 1),
 (2, -1),
 (-1, 3),
 (4, 4),
 (5, 5),
 (6, -1),
 (-1, 7),
 (8, -1),
 (-1, 9),
 (10, 10),
 (11, -1),
 (-1, 12),
 (13, -1),
 (-1, 15),
 (14, -1),
 (-1, 16)]

In [72]:
'a' in c1_set

False

In [75]:
def creates_cycle(connections, test):
    i, o = test
    if i == o:
        return True

    visited = {o}
    while True:
        num_added = 0
        for a, b in connections:
            if a in visited and b not in visited:
                print(visited)
                if b == i:
                    return True

                visited.add(b)
                num_added += 1

        if num_added == 0:
            return False

In [81]:
creates_cycle([(1,2), (2,3), (3,4), (3,5), (5,6), (6,7)], (7,2))

{2}
{2, 3}
{2, 3, 4}
{2, 3, 4, 5}
{2, 3, 4, 5, 6}


True

In [83]:
d = []
for i in range(10):
    d[i] = str(i)
d

{0: '0',
 1: '1',
 2: '2',
 3: '3',
 4: '4',
 5: '5',
 6: '6',
 7: '7',
 8: '8',
 9: '9'}

In [86]:
list(d.keys())[:5]

[0, 1, 2, 3, 4]

In [87]:
l = np.array([5,5,5,4])
l = l / np.sum(l)

In [88]:
l

array([0.26315789, 0.26315789, 0.26315789, 0.21052632])

In [89]:
l[0] = 0.0
l

array([0.        , 0.26315789, 0.26315789, 0.21052632])

In [90]:
l = l / np.sum(l)
l

array([0.        , 0.35714286, 0.35714286, 0.28571429])

In [40]:
import numpy as np
import random

In [41]:
l = [1,2,3,4,5]

In [53]:
for x in random.choices(l, k=3):
    print(x)

5
5
3


In [2]:
x = [1,2,3]
x[:0]

[]

In [3]:
sorted(x)

[1, 2, 3]

In [5]:
import random
import numpy as np

In [10]:
members = [1,2,3,4]
p = np.array([1,1,1]) / 3.0
member_parent_1 = np.random.choice(list(c1_set.keys()), 1, p=p)
member_parent_1

array([1])

In [1]:
import numpy as np
import timeit

x = range(1000)
# or 
#x = np.random.standard_normal(1000)

def pure_sum():
    return sum(x)

def numpy_sum():
    return np.sum(x)

n = 10000

t1 = timeit.timeit(pure_sum, number = n)
print('Pure Python Sum:', t1)
t2 = timeit.timeit(numpy_sum, number = n)
print('Numpy Sum:', t2)

Pure Python Sum: 0.1532475647415019
Numpy Sum: 1.1720797273597179


In [19]:
node_ids = {'all': set([1,2,3,4,5]), 'input': set([1,2]), 'hidden': set([3,4]), 'output': set([5])}
node_ids

{'all': {1, 2, 3, 4, 5}, 'hidden': {3, 4}, 'input': {1, 2}, 'output': {5}}

In [23]:
possible_connections = set()

In [33]:
for source_id in node_ids['input']:
    for target_id in node_ids['hidden']:
        possible_connections.add((source_id, target_id))
    for target_id in node_ids['output']:
        possible_connections.add((source_id, target_id))
        
for source_id in node_ids['hidden']:    
    for target_id in node_ids['hidden']:   
        possible_connections.add((source_id, target_id))
    for target_id in node_ids['output']:
        possible_connections.add((source_id, target_id))
          
possible_connections

{(1, 3),
 (1, 4),
 (1, 5),
 (2, 3),
 (2, 4),
 (2, 5),
 (3, 3),
 (3, 4),
 (3, 5),
 (4, 3),
 (4, 4),
 (4, 5)}

In [34]:
new_hidden_id = 6
node_ids['hidden'].add(6)
node_ids

{'all': {1, 2, 3, 4, 5}, 'hidden': {3, 4, 6}, 'input': {1, 2}, 'output': {5}}

In [37]:
for source_id in node_ids['input']:
    possible_connections.add((source_id, new_hidden_id))
for source_id in node_ids['hidden']:    
    for target_id in node_ids['hidden']:   
        possible_connections.add((source_id, target_id))
for target_id in node_ids['output']:
        possible_connections.add((new_hidden_id, target_id))
        
possible_connections

{(1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6)}

In [38]:
connections = set([(1,3),(1,4),(1,5),(1,6),(6,3),(6,4),(6,5),(6,6)])
connections

{(1, 3), (1, 4), (1, 5), (1, 6), (6, 3), (6, 4), (6, 5), (6, 6)}

In [39]:
possible_connections - connections

{(2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6)}

In [54]:
possible_connections

{(1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6)}

In [55]:
list(possible_connections)

[(6, 4),
 (1, 3),
 (2, 6),
 (3, 3),
 (4, 6),
 (6, 6),
 (4, 5),
 (4, 4),
 (1, 4),
 (6, 3),
 (1, 5),
 (2, 3),
 (1, 6),
 (4, 3),
 (3, 6),
 (2, 5),
 (3, 4),
 (2, 4),
 (6, 5),
 (3, 5)]

In [57]:
random.choice(list(possible_connections))

(6, 5)

In [5]:
n_list_1 = [0, 1, 2, 3]
n_list_2 = [0, 1, 3]

node_pairs = set()
for x in n_list_1:
    if x in n_list_2:
        node_pairs.add((x, x))
    else:
        node_pairs.add((x, -1))
        
for y in n_list_2:
    if y in n_list_1:
        node_pairs.add((y, y))
    else:
        node_pairs.add((-1, y))

In [6]:
node_pairs

{(0, 0), (1, 1), (2, -1), (3, 3)}

In [8]:
import numpy as np

In [10]:
np.random.choice([1,2,3], 6)

array([2, 2, 2, 2, 3, 2])

In [25]:
c_list_1 = [0,1,3,8]
c_list_2 =  [0,1,2,3,4,5,6,7,12]

In [26]:
excess_threshold = min(max(c_list_1), max(c_list_2))
print(excess_threshold)
nb_disjoint, nb_excess = 0, 0
for x in c_list_1:
    if x not in c_list_2:
        if x <= excess_threshold:
            nb_disjoint += 1
        else:
            nb_excess += 1
            
for x in c_list_2:
    if x not in c_list_1:
        if x <= excess_threshold:
            nb_disjoint += 1
        else:
            nb_excess += 1
            
print(nb_disjoint, nb_excess)

8
6 1


In [16]:
import random

In [19]:
l = [random.gauss(0, 1.0) for _ in range(1000000)]
print(min(l), max(l))

-4.679955434689955 4.943377291373051


In [24]:
l = [1,2,3]
l[-100:]

[1, 2, 3]

# Original def's

In [43]:
import itertools

In [145]:
def calc_required_depth(node_ids_all, enabled_connections):
    """
    Calculates the required dependency depth for every node in network
    :return: Node dependency dictionary e.g: {0: [[0]], 1: [[1]], 2: [[2], [0, 1]], 3: [[3], [0, 1, 2]]}
    """
    required = {}
    for n_id in node_ids_all:
        depth_list = [[n_id]]
        while True:
            essential = set(
                source_id for (_, source_id, target_id) in enabled_connections if
                target_id in depth_list[-1] and source_id not in depth_list[-1])
            if not essential:
                break
            depth_list.append(list(essential))
        required[n_id] = depth_list
    return required


def calc_neural_path(depth, n_id, path):
    """
    The function calculates exact order of neuron activations for specified n_id (output id)
    :return: Ordered activation list e.g: [0, 1, 2, 3]
    """
    depth_list = depth[n_id]

    if len(depth_list) == 1:
        # We have reached the end of dependency chain
        if depth_list[0][0] not in path:
            path.append(depth_list[0][0])
    else:
        for depth_set in reversed(depth_list):
            for depth_id in depth_set:
                if n_id == depth_id:
                    if depth_id not in path:
                        path.append(depth_id)
                    break
                calc_neural_path(depth, depth_id, path)


In [149]:
node_ids_all = set([1,2,3,4,5])
connections = [(1,3),(2,4),(3,5),(4,5),(3,4),(3,3),(4,4),(5,5)]
enabled_connections = [(0, x, y) for x, y in connections]

In [150]:
depth = calc_required_depth(node_ids_all, enabled_connections)
depth

{1: [[1]],
 2: [[2]],
 3: [[3], [1]],
 4: [[4], [2, 3], [1]],
 5: [[5], [3, 4], [1, 2]]}

In [151]:
path = []
calc_neural_path(depth, 5, path)
path

[1, 2, 3, 4, 5]

# Modified def's

In [169]:
def calc_required_depth(node_ids_all, enabled_connections):
    required = {}
    for n_id in node_ids_all:
        depth_list = [[n_id]]
        while True:
            essential = set(
                source_id for (_, source_id, target_id) in enabled_connections if
                target_id in depth_list[-1] and source_id not in depth_list[-1] and source_id != n_id)
            if not essential or list(essential) in depth_list:
                break
            depth_list.append(list(essential))
        required[n_id] = depth_list
    return required

def calc_neural_path(depth, n_id, path, searching_for): 
    if n_id in searching_for:
        return
    searching_for.add(n_id)
    depth_list = depth[n_id]  
    if len(depth_list) == 1:
        searching_for.remove(n_id)
        if depth_list[0][0] not in path:
            path.append(depth_list[0][0])
    else:
        for depth_set in reversed(depth_list):
            for depth_id in depth_set:
                if n_id == depth_id:
                    if depth_id not in path:
                        path.append(depth_id)
                    break
                calc_neural_path(depth, depth_id, path, searching_for)

In [170]:
node_ids_all = set([1,2,3,4,5])
connections = [(1,3),(2,4),(3,5),(4,5),(3,4),(3,3),(4,4),(5,5)]
enabled_connections = [(0, x, y) for x, y in connections]

In [171]:
depth = calc_required_depth(node_ids_all, enabled_connections)
depth

{1: [[1]],
 2: [[2]],
 3: [[3], [1]],
 4: [[4], [2, 3], [1]],
 5: [[5], [3, 4], [1, 2]]}

In [172]:
path = []
searching_for = set()
calc_neural_path(depth, 5, path, searching_for)
path

[1, 2, 3, 4, 5]

In [173]:
node_ids_all = set([1,2,3,4,5])
connections = [(1,3),(2,4),(3,5),(4,5),(3,4),(3,3),(4,4),(5,5),(4,3),(5,3),(5,4)]  
enabled_connections = [(0, x, y) for x, y in connections]

In [174]:
depth = calc_required_depth(node_ids_all, enabled_connections)
depth

{1: [[1]],
 2: [[2]],
 3: [[3], [1, 4, 5], [2]],
 4: [[4], [2, 3, 5], [1]],
 5: [[5], [3, 4], [1, 2]]}

In [175]:
path = []
searching_for = set()
calc_neural_path(depth, 5, path, searching_for)
path

[1, 2, 4, 3, 5]

In [176]:
node_ids_all = set([1,2,3,4,5,6,7])
connections = [(1,2),(1,3),(2,5),(3,5),(5,2),(5,3),(7,4),(4,6),(6,4),(4,2)]
enabled_connections = [(0, x, y) for x, y in connections]

In [177]:
depth = calc_required_depth(node_ids_all, enabled_connections)
depth

{1: [[1]],
 2: [[2], [1, 4, 5], [3, 6, 7]],
 3: [[3], [1, 5], [2], [1, 4, 5], [2, 6, 7]],
 4: [[4], [6, 7]],
 5: [[5], [2, 3], [1, 4], [6, 7], [4]],
 6: [[6], [4], [7]],
 7: [[7]]}

In [178]:
path = []
search = set()
calc_neural_path(depth, 6, path, search)
path

[7, 4, 6]

In [179]:
path = []
search = set()
calc_neural_path(depth, 5, path, search)
path

[7, 6, 4, 1, 3, 2, 5]

In [180]:
node_ids_all = set([1,2,3,4,5,6])
connections = [(1,2),(2,3),(3,4),(4,5),(5,2),(3,6),(1,6)]
enabled_connections = [(0, x, y) for x, y in connections]

In [181]:
depth = calc_required_depth(node_ids_all, enabled_connections)
depth

{1: [[1]],
 2: [[2], [1, 5], [4], [3]],
 3: [[3], [2], [1, 5], [4]],
 4: [[4], [3], [2], [1, 5]],
 5: [[5], [4], [3], [2], [1]],
 6: [[6], [1, 3], [2], [1, 5], [4], [3]]}

In [182]:
path = []
search = set()
calc_neural_path(depth, 6, path, search)
path

[1, 2, 5, 4, 3, 6]