In [51]:
d = {1:'a', 2:'b',3: 'c'}

In [52]:
s = list(d.keys())
s

[1, 2, 3]

In [53]:
import numpy as np
from numpy.random import choice

In [54]:
probs = [0.6, 0.2, 0.2]
draw = choice(s, 1, p=probs)
draw

array([2])

In [55]:
rm_idx = s.index(draw)
s.pop(rm_idx)
probs.pop(rm_idx)

0.2

In [56]:
s

[1, 3]

In [57]:
probs

[0.6, 0.2]

In [58]:
np.array(probs) / np.sum(probs)

array([0.75, 0.25])

In [61]:
np.sum(list(d.keys()))

6

In [64]:
for _ in range(10):
    for k in d.values():
        print(k)

a
b
c
a
b
c
a
b
c
a
b
c
a
b
c
a
b
c
a
b
c
a
b
c
a
b
c
a
b
c


In [70]:
p = np.array([1,2,3,5])
p = p / 5
p

array([0.2, 0.4, 0.6, 1. ])

In [78]:
n = np.array(list(d.values()))
n

array(['a', 'b', 'c'], dtype='<U1')

In [86]:
np.array(list(d.keys())) / np.sum(list(d.keys()))

array([0.16666667, 0.33333333, 0.5       ])

In [76]:
list(d.keys())

[1, 2, 3]

In [88]:
d = {1:2.5,2:3.6,3:4.7}
np.array(list(d.values())) / np.sum(list(d.values()))

array([0.23148148, 0.33333333, 0.43518519])

In [97]:
import random
import math
def probabilistic_round(value):
    integer_part = math.floor(value)
    fractional_part = value - integer_part
    return integer_part + 1.0 if random.random() < fractional_part else integer_part + 0.0

In [98]:
for _ in range(20):
    print(probabilistic_round(2.5))

2.0
2.0
3.0
3.0
3.0
2.0
3.0
2.0
2.0
2.0
2.0
3.0
3.0
2.0
2.0
3.0
3.0
2.0
2.0
3.0


In [99]:
2.0 * 5

10.0